Repository 2023-Summer-BootCamp-Team-I/MemoryCapsule, pull requests merged in 2023-07, with the labels that each got.

#11 [FE/feat/#7] Add 페이지 라우팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/common/Background.tsx
  frontend/src/index.css
  frontend/src/pages/CapsuleGalleryPage.tsx
  frontend/src/pages/CreateCapsulePage.tsx
  frontend/src/pages/FirstPage.tsx
  frontend/src/pages/MainOpenedPage.tsx
  frontend/src/pages/MainUnOpenedPage.tsx
  frontend/src/pages/OpenedCapsulePage.tsx
  frontend/src/pages/OpenedStoryPage.tsx
  frontend/src/pages/OpenedVideoPage.tsx
  frontend/src/pages/UnOpenedCapsulePage.tsx
Labels: 환경설정

#27 [BE/feat/26] 캡슐 조회 Get 기능 구현
  .gitignore
  .idea/workspace.xml
  backend/django_back/capsules/serializers.py
  backend/django_back/capsules/views.py
Labels: 기능구현

#36 [FE/feat/#8] 공용컴포넌트 추가(오픈 캡슐 버튼, 입력창, 캡슐)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/assets/images/capsule_label.png
  frontend/src/assets/images/openedCapsule_img1.png
  frontend/src/assets/images/openedCapsule_img2.png
  frontend/src/components/MainOpenCapsule/index.tsx
  frontend/src/components/MainUnopenCapsule/index.tsx
  frontend/src/components/OpenButton/index.tsx
  frontend/src/components/TextInput/index.tsx
  frontend/src/pages/FirstPage.tsx
  frontend/src/pages/MainOpenedPage.tsx
  frontend/src/pages/OpenedCapsulePage.tsx
  frontend/tailwind.config.js
Labels: 기능구현

#39 [FE/feat/#12] 공용 컴포넌트 추가(이미지 업로드 버튼, 참여자 프로필, 스토리)
  frontend/src/App.tsx
  frontend/src/components/ImageUploadButton/index.tsx
  frontend/src/pages/OpenedStoryPage.tsx
Labels: 기능구현

#52 [Feat] 캡슐 정보 수정 api password 반영
  backend/django_back/capsules/models.py
  backend/django_back/capsules/serializers.py
  backend/django_back/capsules/utils.py
  backend/django_back/capsules/views.py
  backend/django_back/images/views.py
  backend/django_back/users/models.py
Labels: 기능구현, 기능수정

#65 [FE/feat/#56] 캡슐 유저 확인 페이지 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ProfileButton/index.tsx
  frontend/src/pages/OpenedVideoPage.tsx
Labels: Design

#62 fix: 스토리 리스트 출력 수정, 출력 메시지 변경
  backend/django_back/stories/views.py
Labels: 기능수정

#97 [FE/feat/#70] 포토 테마 페이지
  frontend/src/assets/images/PhotoTheme/cloud.png
  frontend/src/assets/images/PhotoTheme/cloud2.png
  frontend/src/assets/images/PhotoTheme/heart.png
  frontend/src/assets/images/PhotoTheme/leaf1.png
  frontend/src/assets/images/PhotoTheme/leaf2.png
  frontend/src/assets/images/PhotoTheme/line1.png
  frontend/src/assets/images/PhotoTheme/line2.png
  frontend/src/assets/images/PhotoTheme/star1.png
  frontend/src/assets/images/PhotoTheme/star2.png
  frontend/src/assets/images/note/note4.png
  frontend/src/assets/lottie/sendLodingLottie.json
  frontend/src/components/CreateCapsuleNote/index.tsx
  frontend/src/components/ImageUploadButton/index.tsx
  frontend/src/components/JoinModal/index.tsx
  frontend/src/components/PhotoCard/PhotoCard1/index.tsx
  frontend/src/components/PhotoCard/PhotoCard2/index.tsx
  frontend/src/components/PhotoCard/PhotoCard3/index.tsx
  frontend/src/components/PhotoCard/PhotoCard4/index.tsx
  frontend/src/components/PhotoCard/PhotoCard5/index.tsx
  frontend/src/components/PhotoCard/PhotoCard6/index.tsx
  frontend/src/components/ReactDatePicker/index.tsx
  frontend/src/components/ReactDatePicker/style.module.css
  frontend/src/components/SendLodindLottie/index.tsx
  frontend/src/components/Themes/PhotoTheme/index.tsx
  frontend/src/pages/CreateCapsulePage.tsx
  frontend/src/pages/OpenedStoryPage.tsx
  frontend/src/pages/custom-scrollbar.css
  frontend/tailwind.config.js
Labels: Design

#103 [Fe/feat/#78] 윈도우 테마 디자인
  frontend/src/assets/data/open_my_capsule.ts
  frontend/src/assets/fonts/neo/NeoDunggeunmoPro-Regular.ttf
  frontend/src/assets/fonts/neo/neodgm.ttf
  frontend/src/assets/images/window_theme/document.png
  frontend/src/assets/images/window_theme/document1.png
  frontend/src/assets/images/window_theme/four_menu.png
  frontend/src/assets/images/window_theme/start_logo.png
  frontend/src/components/MainOpenCapsule/index.tsx
  frontend/src/components/Themes/WindowTheme/BottomButton/index.tsx
  frontend/src/components/Themes/WindowTheme/WindowStoryDetail/index.tsx
  frontend/src/components/Themes/WindowTheme/WindowStoryList/index.tsx
  frontend/src/components/Themes/WindowTheme/index.tsx
  frontend/src/index.css
  frontend/src/pages/OpenedStoryPage.tsx
  frontend/src/utils/types.ts
  frontend/tailwind.config.js
Labels: Design

#102 [Be/feat/#90] Docker-compose 파일 및 framework 경로 수정
  .github/workflows/ci.yml
  .gitignore
  appspec.yml
  backend/data/grafana/alerting/1/__default__.tmpl
  backend/data/grafana/grafana.db
  backend/django_back/django_back/urls.py
  backend/monitoring/prometheus/prometheus.yml
  backend/nginx/default.conf
  backend/nginx/nginx.conf
  backend/rabbitmq/enabled_plugins
  docker-compose.yml
  scripts/deploy.sh
Labels: 환경설정

#116 [FE/chore/#105] 캡슐 생성 api
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CreateCapsuleNote/index.tsx
  frontend/src/components/CreateTheme/indext.tsx
  frontend/src/components/ImageUploadButton/index.tsx
  frontend/src/components/ReactDatePicker/index.tsx
  frontend/src/pages/CreateCapsulePage.tsx
Labels: 기능구현

#130 [FE/feat/#125] 스토리 생성/수정/조회 API 연동
  backend/django_back/django_back/views.py
  frontend/src/assets/images/ThemeThumb/museum_theme.png
  frontend/src/assets/images/ThemeThumb/photocard_theme.png
  frontend/src/assets/images/ThemeThumb/window_theme.png
  frontend/src/components/CreateTheme/index.tsx
  frontend/src/components/StoryCreateContent/index.tsx
  frontend/src/components/StoryDetailContent/index.tsx
  frontend/src/components/UnOpenedCapsule/StoryList/index.tsx
  frontend/src/components/common/StoryInput/index.tsx
  frontend/src/pages/CreateCapsulePage.tsx
  frontend/src/pages/OpenedVideoPage.tsx
  frontend/src/pages/UnOpenedCapsulePage.tsx
  frontend/src/utils/types.ts
Labels: 기능구현

#131 [FE/feat/#122] API 연동
  .gitignore
  backend/django_back/capsules/utils.py
  backend/django_back/capsules/views.py
  backend/django_back/django_back/views.py
  backend/django_back/stories/views.py
  frontend/src/App.tsx
  frontend/src/components/CapsuleInfo/index.tsx
  frontend/src/components/CreateCapsuleNote/index.tsx
  frontend/src/components/JoinModal/index.tsx
  frontend/src/components/Login/index.tsx
  frontend/src/components/MainUnopenCapsule/PasswordModal/index.tsx
  frontend/src/components/ProfileButton/index.tsx
  frontend/src/components/StoryCreateContent/index.tsx
  frontend/src/components/UnOpenedCapsule/StoryList/index.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/pages/CreateCapsulePage.tsx
  frontend/src/pages/FirstPage.tsx
  frontend/src/pages/UnOpenedCapsulePage.tsx
  frontend/src/utils/Recoil.tsx
  frontend/src/utils/axios.ts
  frontend/src/utils/types.ts
Labels: 기능구현
